name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
    - nikkisaurus
body:
    - type: input
      attributes:
          label: Interface Version
          placeholder: e.g. 10.0.0
      validations:
          required: true
    - type: input
      attributes:
          label: AddOn Version
          placeholder: e.g. v3.0.0
      validations:
          required: true
    - type: dropdown
      attributes:
          label: Have you replicated this error without any other addons loaded?
          multiple: false
          options:
              - "Yes"
              - "No"
      validations:
          required: true
    - type: textarea
      attributes:
          label: What steps did you take leading up to this issue?
      validations:
          required: true
    - type: textarea
      attributes:
          label: Please supply any screenshots relevant to this issue.
    - type: textarea
      attributes:
          label: Please supply a copy of your saved variables.
          description: ./WTF/Account/YOURACCOUNTNAME/SavedVariables
