name: Package and release stable builds

on:
    push:
        tags:
            - "v*.*.*"
            - "!v*.*.*-*"
            - "!v*.*-*"
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest

        env:
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
            WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Clone project
              uses: actions/checkout@v1

            - name: Package and release for Wrath
              uses: BigWigsMods/packager@master
              with:
                  args: -g wrath

            - name: Package and release for Retail
              uses: BigWigsMods/packager@master
